### ISSUE TITLE
why tableauc.v0.5.7.linux.amd64.tar.gz need GLIBC_2.34 version?

### ISSUE THREAD

**Issue by Andrew-liu** [tableauio/tableau#131]
```
./tableauc: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./tableauc)
./tableauc: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./tableauc)
```

**Comment by Andrew-liu** [comment]
to solve the problem, i change it to v0.5.5, it works well☺

**Comment by wenchy** [comment]
Well, it is a CGO dependency problem which depends on GLIBC. We will build the future releases with `CGO_ENABLED=0` (Static Linking) to avoid this problem.

Thanks for you feedback.

**Comment by Andrew-liu** [comment]
@wenchy please build new version with `CGO_ENABLED=0`, i need the new version feature(v0.5.5 is not support `union`)

thanks

**Comment by wenchy** [comment]
We will release the next version in recent weeks after new important features (YAM support, and patch feature) implemented.

If it is very urgent, you can clone this repo, change dir to *cmd/tableauc*, and build tableauc by yourself: 
```bash
CGO_ENABLED=0 go build -installsuffix cgo -trimpath -ldflags="-s -w"
```

**Comment by Andrew-liu** [comment]
Sorry, I forgot to reply this issue,  I have build cmd tool by your command.
Now It can work for `union feature`, exciting.
Thanks
