### ISSUE TITLE
protogen: support composite indexes (or multicolumn indexes)

### ISSUE THREAD

**Issue by wenchy** [tableauio/tableau#22]
## Syntax
Composite indexes syntax: `([column1, column2, column3,...])[@IndexName]`

Each column type can be:
 - scalar type: `Numbers`, `Booleans`,  and `Strings`
 - enum
 - incell scalar list, e.g: `[]int32`
 - incell enum list, e.g: `[]enum<.FruiteType>`

Examples:

- `ID`
- `ID@Item`
- `(ID,Type)`
- `(ID,Type)@Item`
- `ID, (ID,Type)@Item`

See https://dataschool.com/sql-optimization/multicolumn-indexes/.

## TODO
- [x] Loader(cpp): https://github.com/tableauio/loader

**Comment by m9rco** [comment]
yyds
