### ISSUE TITLE
bug: horizonal list of scalar type doesn't support refer check

### ISSUE THREAD

**Issue by Kybxd** [tableauio/tableau#70]
I add refer check to a horizonal list of uint32
<img width="1069" alt="企业微信截图_16893231816335" src="https://github.com/tableauio/tableau/assets/18246091/61ded18e-012d-461c-bffa-0b3521a731f4">

But this doesn't work, the generated message is as follows (no `refer` prop generated):
```proto
message RuneSuitRecommendConf {
  option (tableau.worksheet) = {name:"Sheet1" namerow:1 typerow:2 noterow:3 datarow:5 nameline:1 typeline:2};

  map<uint32, Suit> suit_map = 1 [(tableau.field) = {key:"SuitID" layout:LAYOUT_VERTICAL}];
  message Suit {
    uint32 suit_id = 1 [(tableau.field) = {name:"SuitID"}];
    repeated uint32 red_rune_list = 2 [(tableau.field) = {name:"RedRune" layout:LAYOUT_HORIZONTAL prop:{fixed:true}}];
    repeated uint32 blue_rune_list = 3 [(tableau.field) = {name:"BlueRune" layout:LAYOUT_HORIZONTAL prop:{fixed:true}}];
    repeated uint32 green_rune_list = 4 [(tableau.field) = {name:"GreenRune" layout:LAYOUT_HORIZONTAL prop:{fixed:true}}];
  }
}
```

**Comment by wenchy** [comment]
Yes, currently, horizonal list of scalar type doesn't support `refer` check, only scalar type in struct support `refer` check.
You can use `horizonal list of struct type` instead:
| Rune1ID | Rune2ID | Rune3ID |
|--------|--------|--------|
| [Rune]uint32\|{refer:"XXXConf.RuneID"}| uint32| uint32|
